contact_links:
  - name: ‚ùì Support question
    url: https://github.com/capawesome-team/capacitor-plugins/discussions
    about: This issue tracker is not for support questions. Please post your question on GitHub Discussions.
